SELECT * FROM shopping limit 20


--1.What is the total revenue generated by male vs. female customers?

select gender, SUM("purchase_amount_(usd)") as revenue
from shopping
group by gender
--2. Which customers used the discount but still spent more than the average purchase amount.


select customer_id, "purchase_amount_(usd)"
from shopping
where discount_applied ='yes' and purchase_amount >= (select AVG("purchase_amount_(usd)") from shopping)



--3. Which are the top five products with the highest average review rating? 


select item_purchased, ROUND(AVG(review_rating::numeric),2)as "Average product rating"
from shopping
group by  item_purchased
order by avg(review_rating) desc
limit 5;




--4. Do subscribed customers spend more compare average spend and total revenue between subscribers and non subscribers.

select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG("purchase_amount_(usd)"),2) as avg_spend,
ROUND(SUM("purchase_amount_(usd)"),2) as total_revenue
from shopping
group by subscription_status
order by total_revenue, avg_spend desc;


--5. Which five products have the highest percentage of purchases with discount applied? 


select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from shopping
group by item_purchased
order by discount_rate desc
limit 5;



--6. Segment customers into new ,returning and loyal based on their total number of previous purchases, 
--and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from shopping
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment



--7. What are the top three most purchased product within each category? 

with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from shopping
group by category, item_purchased
)


select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;




--8. Are customers who are repeat buyers (more than 5 previous purchases )also likely to subscribe? 


select subscription_status,
count(customer_id) as repeat_buyers
from shopping
where previous_purchases > 5
group by subscription_status


--9. What is the revenue contribution of each is group? 

select age,
SUM("purchase_amount_(usd)") as total_revenue
from shopping
group by age
order by total_revenue desc;